/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AuthService } from "./auth.service";
export { ClubesService } from "./clubes.service";
export { EmprestimosService } from "./emprestimos.service";
export { ExemplaresService } from "./exemplares.service";
export { GenerosService } from "./generos.service";
export { InstituicaoService } from "./instituicao.service";
export { ItemPerguntaService } from "./itemPergunta.service";
export { LivroGeneroService } from "./livroGenero.service";
export { LivrosService } from "./livros.service";
export { MembroClubeService } from "./membroClube.service";
export { PerguntasService } from "./perguntas.service";
export { PreferenciasGeneroService } from "./preferenciasGenero.service";
export { RespostaMembroService } from "./respostaMembro.service";
export { UsuariosService } from "./usuarios.service";
