/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for MembroClube controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CreateMembroClubeDto, UpdateMembroClubeDto } from "../models";

@Injectable({ providedIn: "root" })
export class MembroClubeService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    membroClubeControllerFindAll(clubeId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerFindAll(clubeId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerFindAll(clubeId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerFindAll(clubeId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube`;

        let params = new HttpParams();
        if (clubeId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, clubeId, 'clube_id');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    membroClubeControllerFindMinhaInscricao(clubeId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerFindMinhaInscricao(clubeId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerFindMinhaInscricao(clubeId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerFindMinhaInscricao(clubeId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube/me/${clubeId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        }else{
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    membroClubeControllerCreate(createMembroClubeDto: CreateMembroClubeDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerCreate(createMembroClubeDto: CreateMembroClubeDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerCreate(createMembroClubeDto: CreateMembroClubeDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerCreate(createMembroClubeDto: CreateMembroClubeDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createMembroClubeDto, requestOptions);
    }

    membroClubeControllerFindOne(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerFindOne(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerFindOne(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerFindOne(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    membroClubeControllerUpdate(id: string, updateMembroClubeDto: UpdateMembroClubeDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerUpdate(id: string, updateMembroClubeDto: UpdateMembroClubeDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerUpdate(id: string, updateMembroClubeDto: UpdateMembroClubeDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerUpdate(id: string, updateMembroClubeDto: UpdateMembroClubeDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, updateMembroClubeDto, requestOptions);
    }

    membroClubeControllerRemove(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    membroClubeControllerRemove(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    membroClubeControllerRemove(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    membroClubeControllerRemove(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/membro-clube/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
