/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for PreferenciasGenero controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CreatePreferenciaGeneroDto, UpdatePreferenciaGeneroDto } from "../models";

@Injectable({ providedIn: "root" })
export class PreferenciasGeneroService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    preferenciaGeneroControllerFindAll(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    preferenciaGeneroControllerFindAll(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    preferenciaGeneroControllerFindAll(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    preferenciaGeneroControllerFindAll(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/preferencias-genero`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    preferenciaGeneroControllerCreate(createPreferenciaGeneroDto: CreatePreferenciaGeneroDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    preferenciaGeneroControllerCreate(createPreferenciaGeneroDto: CreatePreferenciaGeneroDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    preferenciaGeneroControllerCreate(createPreferenciaGeneroDto: CreatePreferenciaGeneroDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    preferenciaGeneroControllerCreate(createPreferenciaGeneroDto: CreatePreferenciaGeneroDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/preferencias-genero`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createPreferenciaGeneroDto, requestOptions);
    }

    preferenciaGeneroControllerUpdatePreferencias(updatePreferenciaGeneroDto: UpdatePreferenciaGeneroDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    preferenciaGeneroControllerUpdatePreferencias(updatePreferenciaGeneroDto: UpdatePreferenciaGeneroDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    preferenciaGeneroControllerUpdatePreferencias(updatePreferenciaGeneroDto: UpdatePreferenciaGeneroDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    preferenciaGeneroControllerUpdatePreferencias(updatePreferenciaGeneroDto: UpdatePreferenciaGeneroDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/preferencias-genero/me/generos`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, updatePreferenciaGeneroDto, requestOptions);
    }

    preferenciaGeneroControllerFindOne(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    preferenciaGeneroControllerFindOne(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    preferenciaGeneroControllerFindOne(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    preferenciaGeneroControllerFindOne(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/preferencias-genero/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    preferenciaGeneroControllerRemove(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    preferenciaGeneroControllerRemove(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    preferenciaGeneroControllerRemove(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    preferenciaGeneroControllerRemove(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/preferencias-genero/${id}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
