/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface CreateUsuarioDto {
    /** ÍD da instituição */
    instituicao_id: string;
    /** Foto de perfil do usuário */
    foto_perfil: string;
    /** Data de nascimento do usuário */
    data_nasc: Date;
    /** Nome do usuário */
    nome: string;
    /** E-mail do usuário */
    email: string;
    /** Senha do usuário */
    senha: string;
    /** Tipo de perfil do usuário */
    perfil: 'gestor' | 'bibliotecario' | 'professor' | 'aluno';
}

export interface UpdateUsuarioDto {
    /** Foto de perfil do usuário */
    foto_perfil: string;
    /** Nome do usuário */
    nome: string;
    /** Data de nascimento do usuário */
    data_nasc: Date;
    /** Senha do usuário */
    senha: string;
}

export interface CreateRespostaMembroDto {
    /** ID do membro relacionado ao clube */
    membro_id: string;
    /** ID do item da pergunta relacionado ao clube */
    item_pergunta_id: string;
}

export interface CreateMembroClubeDto {
    /** ID do clube do livro relacionado */
    clube_id: string;
    /** ID do usuário relacionado */
    usuario_id: string;
    /** Status do membro no clube */
    status: 'pendente' | 'confirmado' | 'cancelado' | 'finalizado';
}

export interface UpdateMembroClubeDto {
    /** ID do clube do livro relacionado */
    clube_id?: string;
    /** ID do usuário relacionado */
    usuario_id?: string;
    /** Status do membro no clube */
    status?: 'pendente' | 'confirmado' | 'cancelado' | 'finalizado';
}

export interface CreateClubeLivroDto {
    /** ID do professor responsável pelo clube */
    professor_id: string;
    /** ID do livro do clube */
    livro_id: string;
    /** Nome do clube */
    nome: string;
    /** Data de início do clube */
    data_inicio?: Record<string, unknown>;
    /** Data de termino do clube */
    data_fim?: Record<string, unknown>;
    /** local ou link de encontro */
    local_encontro?: Record<string, unknown>;
}

export interface UpdateClubeLivroDto {
    /** ID do professor responsável pelo clube */
    professor_id?: string;
    /** ID do livro do clube */
    livro_id?: string;
    /** Nome do clube */
    nome?: string;
    /** Data de início do clube */
    data_inicio?: Record<string, unknown>;
    /** Data de termino do clube */
    data_fim?: Record<string, unknown>;
    /** local ou link de encontro */
    local_encontro?: Record<string, unknown>;
}

export interface CreateLivroDto {
    /** ID da Instituição */
    instituicao_id: string;
    /** Título da Obra */
    titulo: string;
    /** Autor */
    autor: string;
    /** Código ISBN */
    isbn?: string;
    editora?: string;
    ano_publicacao?: number;
    /** Resumo do livro */
    sinopse?: string;
    capa_url?: string;
    faixa_etaria?: 'livre' | '10+' | '12+' | '14+' | '16+' | '18+';
}

export interface UpdateLivroDto {
    /** ID da Instituição */
    instituicao_id?: string;
    /** Título da Obra */
    titulo?: string;
    /** Autor */
    autor?: string;
    /** Código ISBN */
    isbn?: string;
    editora?: string;
    ano_publicacao?: number;
    /** Resumo do livro */
    sinopse?: string;
    capa_url?: string;
    faixa_etaria?: 'livre' | '10+' | '12+' | '14+' | '16+' | '18+';
}

export interface CreatePreferenciaGeneroDto {
    /** ID do usuário */
    usuario_id: string;
    /** ID do gênero */
    genero_id: string;
}

export interface CreateLivroGeneroDto {
    /** ID do livro */
    livro_id: string;
    /** ID do gênero literário */
    genero_id: string;
}

export interface CreateInstituicaoDto {
    /** Nome da instituição */
    nome: string;
    /** Tipo de instituição */
    tipo: 'escola' | 'faculdade';
    /** Cidade onde se localiza a instituição */
    cidade: string;
    /** Estado onde se localiza a instituição */
    estado: string;
}

export interface UpdateInstituicaoDto {
    /** Nome da instituição */
    nome?: string;
    /** Tipo de instituição */
    tipo?: 'escola' | 'faculdade';
    /** Cidade onde se localiza a instituição */
    cidade?: string;
    /** Estado onde se localiza a instituição */
    estado?: string;
}

export interface CreateExemplarDto {
    /** ID do livro */
    livro_id: string;
    /** Código do exemplar */
    codigo: string;
    status: 'disponivel' | 'emprestado' | 'danificado' | 'perdido';
}

export interface UpdateExemplarDto {
    /** ID do livro */
    livro_id?: string;
    /** Código do exemplar */
    codigo?: string;
    status?: 'disponivel' | 'emprestado' | 'danificado' | 'perdido';
}

export interface CreateEmprestimoDto {
    /** ID do exemplar */
    exemplar_id: string;
    /** ID do usuário */
    usuario_id: string;
    /** Data de retirada do empréstimo */
    data_retirada: Date;
    /** Data prevista para devolução */
    data_devolucao_esperada: Date;
    /** Data efetiva de devolução */
    data_devolucao_efetiva?: Date;
}

export interface UpdateEmprestimoDto {
    /** ID do exemplar */
    exemplar_id?: string;
    /** ID do usuário */
    usuario_id?: string;
    /** Data de retirada do empréstimo */
    data_retirada?: Date;
    /** Data prevista para devolução */
    data_devolucao_esperada?: Date;
    /** Data efetiva de devolução */
    data_devolucao_efetiva?: Date;
}

export interface LoginDto {
    /** E-mail do usuário */
    email: string;
    /** Senha do usuário */
    senha: string;
}

export interface RefreshTokenDto {
    /** Token antigo para refresh */
    token: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
